export const WEATHER_EVENT_PRODUCT_SCHEMA = 'satellite-wars.weather-events.v1';
export const WEATHER_EVENT_LEDGER_SCHEMA = 'satellite-wars.weather-event-ledger.v1';

export const WEATHER_EVENT_TYPES = Object.freeze({
  EXTRATROPICAL_CYCLONE: 'extratropical-cyclone',
  FRONT: 'front',
  TROPICAL_DISTURBANCE: 'tropical-disturbance',
  HURRICANE: 'hurricane',
  MCS: 'mcs',
  SUPERCELL: 'supercell',
  TORNADO_OUTBREAK: 'tornado-outbreak',
  MONSOON_BURST: 'monsoon-burst',
  DUST_EVENT: 'dust-event',
  BLIZZARD: 'blizzard',
  ATMOSPHERIC_RIVER: 'atmospheric-river'
});

export const WEATHER_EVENT_TYPE_LIST = Object.freeze(Object.values(WEATHER_EVENT_TYPES));

export const WEATHER_EVENT_MATCH_RADIUS_KM = Object.freeze({
  [WEATHER_EVENT_TYPES.EXTRATROPICAL_CYCLONE]: 1050,
  [WEATHER_EVENT_TYPES.FRONT]: 900,
  [WEATHER_EVENT_TYPES.TROPICAL_DISTURBANCE]: 850,
  [WEATHER_EVENT_TYPES.HURRICANE]: 950,
  [WEATHER_EVENT_TYPES.MCS]: 650,
  [WEATHER_EVENT_TYPES.SUPERCELL]: 420,
  [WEATHER_EVENT_TYPES.TORNADO_OUTBREAK]: 600,
  [WEATHER_EVENT_TYPES.MONSOON_BURST]: 900,
  [WEATHER_EVENT_TYPES.DUST_EVENT]: 750,
  [WEATHER_EVENT_TYPES.BLIZZARD]: 850,
  [WEATHER_EVENT_TYPES.ATMOSPHERIC_RIVER]: 1100
});

export const WEATHER_EVENT_MAX_ACTIVE_BY_TYPE = Object.freeze({
  [WEATHER_EVENT_TYPES.EXTRATROPICAL_CYCLONE]: 8,
  [WEATHER_EVENT_TYPES.FRONT]: 12,
  [WEATHER_EVENT_TYPES.TROPICAL_DISTURBANCE]: 8,
  [WEATHER_EVENT_TYPES.HURRICANE]: 5,
  [WEATHER_EVENT_TYPES.MCS]: 8,
  [WEATHER_EVENT_TYPES.SUPERCELL]: 6,
  [WEATHER_EVENT_TYPES.TORNADO_OUTBREAK]: 4,
  [WEATHER_EVENT_TYPES.MONSOON_BURST]: 6,
  [WEATHER_EVENT_TYPES.DUST_EVENT]: 6,
  [WEATHER_EVENT_TYPES.BLIZZARD]: 6,
  [WEATHER_EVENT_TYPES.ATMOSPHERIC_RIVER]: 6
});

export const WEATHER_EVENT_RETIRE_AFTER_SECONDS = Object.freeze({
  [WEATHER_EVENT_TYPES.EXTRATROPICAL_CYCLONE]: 30 * 3600,
  [WEATHER_EVENT_TYPES.FRONT]: 24 * 3600,
  [WEATHER_EVENT_TYPES.TROPICAL_DISTURBANCE]: 36 * 3600,
  [WEATHER_EVENT_TYPES.HURRICANE]: 48 * 3600,
  [WEATHER_EVENT_TYPES.MCS]: 8 * 3600,
  [WEATHER_EVENT_TYPES.SUPERCELL]: 3 * 3600,
  [WEATHER_EVENT_TYPES.TORNADO_OUTBREAK]: 6 * 3600,
  [WEATHER_EVENT_TYPES.MONSOON_BURST]: 24 * 3600,
  [WEATHER_EVENT_TYPES.DUST_EVENT]: 18 * 3600,
  [WEATHER_EVENT_TYPES.BLIZZARD]: 24 * 3600,
  [WEATHER_EVENT_TYPES.ATMOSPHERIC_RIVER]: 24 * 3600
});
